name: Continuous Integration
on: 
   push:
    paths-ignore:
      - 'READ.md'
   pull_request:
    paths-ignore:
      - 'READ.md'


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag todo-app:test --target test .
    - run: docker run todo-app:test